### ISSUE TITLE
Release 1.1: Regression breaks setuptools builds

### ISSUE THREAD

**Issue by jaraco** [pypa/pyproject-hooks#192] opened 2024-04-29 19:21 UTC
In https://github.com/pypa/setuptools/issues/4333, setuptools reports some emergent failures implicating the recent pyproject-hooks 1.1 release.

**Comment by jaraco** [comment] 2024-04-29 19:25
I suspect [this change is relevant](https://github.com/pypa/pyproject-hooks/blob/60a72a084b1f6cf64aa4be49aa1e971511cc5659/docs/changelog.rst?plain=1#L8-L12).

**Comment by pradyunsg** [comment] 2024-04-29 19:36
https://github.com/pypa/pyproject-hooks/pull/165 is the relevant PR -- /cc @abravalheri for awareness.

It's unclear to me what exactly is happening here from the setuptools failure, so not quite sure what the fix should/would be?

**Comment by jaraco** [comment] 2024-04-29 19:50
My initial thought is that setuptools' builds were previously relying on metadata from an existing installation... and this change keeps that metadata hidden so that all that's around is the bootstrap metadata, which isn't sufficient to build setuptools (maybe?).

**Comment by jaraco** [comment] 2024-04-29 19:52
Or, maybe the changes to avoid altering `sys.path` cause the metadata to be missing altogether.

**Comment by pradyunsg** [comment] 2024-04-29 19:58
The `sys.path` with 1.0.0:

> ['/Users/pradyunsg/Developer/github/setuptools', '/Users/pradyunsg/Developer/github/setuptools/.venv/lib/python3.12/site-packages/pyproject_hooks/_in_process', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python312.zip', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python3.12', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python3.12/lib-dynload', '/Users/pradyunsg/Developer/github/setuptools/.venv/lib/python3.12/site-packages']

The `sys.path` with 1.1.0:

> ['/Users/pradyunsg/Developer/github/setuptools/.venv/lib/python3.12/site-packages/pyproject_hooks/_in_process', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python312.zip', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python3.12', '/Users/pradyunsg/.asdf/installs/python/3.12.0/lib/python3.12/lib-dynload', '/Users/pradyunsg/Developer/github/setuptools/.venv/lib/python3.12/site-packages']

It's... suboptimal... that `_in_process` is on sys.path with this setup.

**Comment by pradyunsg** [comment] 2024-04-29 20:14
Yup, it's the changeover to using `sys.meta_path` rather than `sys.path` for loading the backend that's affected things here.

**Comment by jaraco** [comment] 2024-04-29 21:11
I suspect adding a `find_distributions` (i.e. making it an importlib.metadata.DistributionFinder) will allow it to find the metadata for a backend and will likely address the concern.

**Comment by mdagost** [comment] 2024-04-29 23:26
I also suspect this is the root cause of this issue: https://github.com/python-poetry/poetry/issues/9351

**Comment by pradyunsg** [comment] 2024-04-30 00:10
@mdagost No. See #191.

**Comment by mdagost** [comment] 2024-04-30 00:15
Yes.  Simply downgrading `pyproject-hooks` from 1.1.0 to 1.0.0 with no other changes fixes poetry install for all our projects.

**Comment by mdagost** [comment] 2024-04-30 01:06
Sorry--update.  I believe the root cause is that 1.0.0 was locked in the `poetry.lock` file, but then poetry itself pulled in 1.1.0 when it was pip installed.  So there was a conflict.  Either downgrading to 1.0.0 after pip installing, _or_ upgrading to 1.1.0 in the lock file fixes things for me.

**Comment by pradyunsg** [comment] 2024-04-30 08:44
@mdagost That sounds unrelated to this project, and specific to how Poetry is handling its environment and lockfile.

**Comment by mdagost** [comment] 2024-04-30 18:59
Correct.  The root root cause was managing poetry with the lockfile, which is no bueno.

**Comment by nanonyme** [comment] 2024-06-18 20:58
@pradyunsg is this now actually fixed with that merged PR and pending release or is there no fix yet?

**Comment by jacobfriedman** [comment] 2024-06-19 05:20
CPython should stop shipping with prebuilt pip and invoking an install of prebuilt setuptools. Even [Fedora](https://github.com/fedora-riscv/python-setuptools/commit/b3c9e12e27c49fde68871f19669a49b507fd487d) has a problem with this.

**Comment by nanonyme** [comment] 2024-07-18 16:10
@jacobfriedman CPython shipping pip has absolutely nothing to do with this problem, this same issue happens with pyproject stack with no pip and only build+installer.

**Closed** 2024-09-29 08:59 UTC
